### ISSUE TITLE
Unifi protect running but NO IP and the phone app shows camera lost power. 

### ISSUE THREAD

**Issue by rkbest13** [markdegrootnl/unifi-protect-x86#10]
I have unifi protect up and running in ubunut VM+docker. I can access it on IP:7080 and it shows add camera screen and one offline camera as 172.18.0.2. 
I creates a proxy cam with bigbuckbunny video to test but nothing is seems working. 
How do I troubleshoot this?
![image](https://user-images.githubusercontent.com/64113851/166736923-b2fd897b-b6c7-434d-ae04-2a75dd1958dc.png)
![image](https://user-images.githubusercontent.com/64113851/166737363-565bd0ea-d656-4f87-a7d2-4f08b69249a9.png)

**Comment by markdegrootnl** [comment]
What is this Proxy Cam?

You can start debugging in the log files at `/srv/unifi-protect/logs` inside the container.

**Comment by rkbest13** [comment]
Thank you! 
mite another interesting project that shows using any Poe camera to be added to unifi not just unifi
