### ISSUE TITLE
UniFi Protect V1.17.1 Connecting to your NVR

### ISSUE THREAD

**Issue by ryanmead22** [markdegrootnl/unifi-protect-x86#12]
Hi, 

I have installed UniFi Protect x86 version in docker using the latest release. 

I have gone through the setup wizard and have logged in. 

However, it always hangs at "Connecting to your NVR". I have tried re installing the OS (Ubuntu 20.04) & re installing docker. 

![image](https://user-images.githubusercontent.com/117681997/200400234-b22cd0b1-3bd7-41a5-9fc4-93e9e9dfaf36.png)

Do you have any suggestions on how this could be fixed?

Thanks, 

Ryan

**Comment by Buster14** [comment]
Same issue here, any chance to fix this? @markdegrootnl
