### ISSUE TITLE
Docker container keeps crashing

### ISSUE THREAD

**Issue by thierrybla** [markdegrootnl/unifi-protect-x86#2]
Hi,

I run docker on Ubuntu 20.04 and would like to run this container.

However I keep getting this error:

`
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".
Data page checksums are disabled.

initdb: could not change permissions of directory "/var/lib/postgresql/10/main": Operation not permitted
fixing permissions on existing directory /var/lib/postgresql/10/main ... 
`

I tried everything but it still doesn't work even 777 doesn't work.

Any help would be appreciated.

**Comment by aolley** [comment]
Try setting chown 101:103 on the folder you're storing the database data in. That's the uid/gid the container is using for the postgres user.

**Comment by redno2** [comment]
Thanks I've had the same issue..
I've make two proposal in PRs #8 #9

**Comment by jbartlett777** [comment]
I also needed to enter: chown -R 999:999 data
