### ISSUE TITLE
G3 Instant?

### ISSUE THREAD

**Issue by 9dc** [markdegrootnl/unifi-protect-x86#3]
How am i able to add a G3 Instant to the protect?
Im not able to select it..

![image](https://user-images.githubusercontent.com/11146776/134908644-04576080-22da-4d2b-b584-0fea847d498b.png)

**Comment by markdegrootnl** [comment]
Hi 9dc, 

I don't think the G3 Instant is supported in UniFi Protect 1.13.3, which unfortunately is the latest version for x86 architecture. 

You could check out my build for arm64, like the Raspberry Pi model 4: https://github.com/markdegrootnl/unifi-protect-arm64
