### ISSUE TITLE
any way to get this updated to the latest release?

### ISSUE THREAD

**Issue by FrederikLeed** [markdegrootnl/unifi-protect-x86#6]
Like can I do it myself somehow or?

**Comment by CorneliousJD** [comment]
> Like can I do it myself somehow or?

I can answer this one - I am not creator/maintainer of this project but 
"This is the x86 (amd64) version. UniFi stopped supporting x86 at version 1.13.3"
There wont be any updates to this beyond 1.13.3 
1.14 and further require UniFi hardware. 

![image](https://user-images.githubusercontent.com/724777/148630725-4421ab8e-14ec-443d-b176-30db92c48e4b.png)

**Comment by markdegrootnl** [comment]
Thanks @CorneliousJD, you are correct
